language: node_js
node_js:
  - 6
cache:
  directories:
    - ~/.npm
    - node_modules
#install:
 # - npm install
script:
 - $(npm bin)/cypress run --record --key 29398af2-7ed1-4590-8d39-c6046e153b51
