@@ -11,10 +11,7 @@ install:
    # Output useful info for debugging.
    - node --version
    - npm --version
 -  - npm install --production
 -  - echo Installing %CYPRESS_NPM_PACKAGE_NAME%
 -  - echo binary version %CYPRESS_BINARY_VERSION%
 -  - npm install %CYPRESS_NPM_PACKAGE_NAME%
 +  - npm install
  
  # Post-install test scripts.
  test_script:
